# general config
model_class: 'plastics'

# data sources
input_data_path: '../simson_data/data/plastics/output'

# model customization
customization:
  stock_extrapolation_class_name: 'SigmoidExtrapolation'
  do_gdppc_time_regression: True # if True, gdppc is already log-transformed, so do not choose 'LogSigmoidExtrapolation'
  lifetime_model_name: 'NormalLifetime'
  do_stock_extrapolation_by_category: True

# visualization
visualization:
  do_visualize: True
  use_stock:
    do_visualize: True
    # options: 'time', 'gdppc'
    # over: 'gdppc'
    over_gdp: True
    acc: True
    per_capita: True
  production:
    do_visualize: True
  extrapolation:
    do_visualize: True
  sankey:
    do_visualize: True
    slice_dict:
      t: 2050
      #r: "CHA"
    exclude_processes:
      - "sysenv"
      - "waste_market"
      - "primary_market"
      - "intermediate_market"
      - "good_market"

    exclude_flows: [ ]
  flows:
    do_visualize: True
    
  do_show_figs: True
  do_save_figs: False

# data export
output_path: 'data/plastics/output'
do_export:
  pickle: False
  csv: True
  iamc: True
