# general config
model_class: 'steel'

# data sources
input_data_path: '../simson_data/data/steel/output'

# model customization
customization:
  mode: 'stock_driven'
  stock_extrapolation_class_name: 'LogSigmoidExtrapolation'
  lifetime_model_name: 'LogNormalLifetime'
  do_stock_extrapolation_by_category: True

# visualization
visualization:
  do_visualize: True
  scrap_demand_supply:
    do_visualize: True
  sector_splits:
    do_visualize: True
  use_stock:
    do_visualize: True
    over_gdp: True
    per_capita: True
  gdppc:
    do_visualize: True
    per_capita: True
  production:
    do_visualize: True
  consumption:
    do_visualize: True
  trade:
    do_visualize: True
  sankey:
    do_visualize: True
    slice_dict:
      t: 2050
      r: 'CHA'
    exclude_processes:
      - "sysenv"
      #- "imports"
      #- "exports"
    exclude_flows: [ ]
  do_show_figs: True
  do_save_figs: False
  plotting_engine: 'plotly'

# data export
output_path: 'data/steel/output'
do_export:
  pickle: False
  csv: False
  future_input: False
  iamc: True
